# Generated by Django 6.0.5 on 2026-06-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='long_url',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
